name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: basic-nginx
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx
    - name: Build and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: ./basic-nginx
        file: ./basic-nginx/Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/basic-nginx:latest
        push: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
