name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: basic-nginx
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push to registry
      uses: docker/build-push-action@v2
      with:
        context: ./basic-nginx
        file: ./basic-nginx/Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/basic-nginx:latest
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
